# Generated by Django 4.2.30 on 2026-09-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('order_date', models.DateTimeField()),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'order_id')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_settled', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('fully_reconciled', 'Fully Reconciled'), ('amount_mismatch', 'Amount Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('missing_payment', 'Missing Payment'), ('orphan_payment', 'Orphan Payment'), ('duplicate_payment', 'Duplicate Payment'), ('status_mismatch', 'Status Mismatch'), ('data_quality', 'Data Quality Issue')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('llm_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='api.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to='api.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
