# Generated by Django 4.2.30 on 2026-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'order_id'], name='api_order_user_id_69db4e_idx'),
        ),
    ]
